name: morchid_hub
description: Plateforme de tourisme durable au Maroc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4  # ✅ NOUVEAU
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0


  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Si vous utilisez Google Fonts (recommandé)
  # Ajoutez cette dépendance:
  # google_fonts: ^6.1.0